version: '3'

services:
  frontend:
    build: './frontend'
    depends_on: 
    - backend
    ports: 
    - 3000:3000
    environment:
    - REACT_APP_API_URL=http://localhost:8080 # interesting, service discovery didn't work with fetch api.
  backend:
    build: './backend'
    ports: 
    - 8080:8080